### ISSUE TITLE
Add --no-pager option to avoid long line issue in smaller terminal windows

### ISSUE THREAD

**Issue by go140point6** [inv4fee2020/pli_node_conf#13]
In base_sys_setup, line 233, change to:

`sudo systemctl start ufw && sudo systemctl status ufw --no-pager`

This will ignore the long lines of output so it doesn't pause the script.  Basically you can test this pretty easily in putty simply by making your terminal window small and running 

`sudo systemctl status ufw`

and then again with the --no-pager option

`sudo systemctl status ufw --no-pager`

I didn't actually try running the script in full with this option, so it might be needed elsewhere.  And perhaps it would be good to add to line 275 as well just in case.

**Comment by inv4fee2020** [comment]
will implement in dev and verify the effects before pushing to main

**Comment by inv4fee2020** [comment]
tested in ufw-pager branch ok. have not been able to replicate the issue encountered by some so inconclusive from my perspective.

**Comment by inv4fee2020** [comment]
further testing with extremely minimal terminal window has replicated the issue.  --no-pager has had no impact.  user input of 'q' + 'enter' is required to bypass
